name: mvvm_plus
description: A Flutter implementation of MVVM plus support for sharing business logic across widgets.
version: 0.1.4
repository: https://github.com/buttonsrtoys/mvvm_plus
issue_tracker: https://github.com/buttonsrtoys/mvvm_plus/issues

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  registrar: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true